config/routes.rb
Rails.application.routes.draw do
  

  devise_for :admins, module: 'admins' 

  devise_scope :user do
    get "sign_in", to: "users/sessions#new", :as => :login
  end

  devise_for :users, module: 'users' 

  scope '/decision7' do
    resources :requests

    resources :comments

    resources :bugs, :path => 'tickets'
  end

  scope '/ignitetek' do  
    resources :requests

    resources :comments

    resources :bugs, :path => 'tickets'

  end

  get "how-to", to: "how_to#index"

  get 'home/index'

  match '/email_suggestions', to: 'email_suggestions#index', via: :get

	root "home#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :bug
	belongs_to :request
	has_many :images, :dependent => :destroy

	validates_presence_of :user_name
  validates_length_of :user_name, :within => 2..20
  validates_presence_of :body
  paginates_per 10
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @comments = Comment.all
  end

  def show
    respond_type
  end

  def new
    @comment = Comment.new
    respond_type
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)

    @comment.story_id = @story_id
    if @comment.save
      if params[:comment][:images]
        params[:comment][:images].each { |image|
          @comment.images.create(image: image)
        }
      end
    end

    if !@comment.bug_id
      @request = Trello::Card.find(@comment.request.task_id)
      @request.add_comment(create_detailed_comment)
      RequestCommentCreator.delay.send_request_comment_notifier_email(@comment)
    else
      @bug = Trello::Card.find(@comment.bug.task_id)
      @bug.add_comment(create_detailed_comment)
      CommentCreator.delay.send_comment_notifier_email(@comment)
    end

    if !@comment.request_id && Bug.find(params[:comment][:bug_id]).org.to_i != 0
      redirect_to("/decision7/tickets/#{@comment.bug_id}")
    elsif !@comment.bug_id && Request.find(@comment.request_id).org.to_i != 0
      redirect_to("/decision7/tickets/#{@comment.request_id}")
    elsif !@comment.request_id && Bug.find(@comment.bug_id).org.to_i == 0
      redirect_to("/ignitetek/tickets/#{@comment.bug_id}")
    else
      redirect_to("/ignitetek/tickets/#{@comment.request_id}")
    end
  end

  def update
    @comment.update(comment_params)
    respond_type
  end

  def destroy
    @comment.destroy
    respond_type
  end

  private

    def create_detailed_comment
      return "Comment Body- #{@comment.body}"
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def respond_type
      if !@comment.bug_id
        redirect_to(@comment.request)
      else
        redirect_to(@comment.bug)
      end
    end

    def comment_params
      params.require(:comment).permit(:user_name, :body, :bug_id, :request_id, images: [:image])
    end
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <% if admin_signed_in? %>
      <%= f.text_field :user_name, :value => current_admin.name %>
    <% else %>
      <%= f.text_field :user_name %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="row">
    <div class="twelve columns">
      <%= f.label :images %>
      <%= f.file_field :images, type: :file, multiple: true %>
    </div>
  </div>
  <%= f.hidden_field :bug_id %>
  <%= f.hidden_field :request_id %>
  <div class="actions">
    <%= f.submit class: 'comment-submit' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Body</th>
      <th>Bug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.bug_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Bug:</strong>
  <%= @comment.bug_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>