config/routes.rb
Rails.application.routes.draw do
  

  devise_for :admins, module: 'admins' 

  devise_scope :user do
    get "sign_in", to: "users/sessions#new", :as => :login
  end

  devise_for :users, module: 'users' 

  scope '/decision7' do
    resources :requests

    resources :comments

    resources :bugs, :path => 'tickets'
  end

  scope '/ignitetek' do  
    resources :requests

    resources :comments

    resources :bugs, :path => 'tickets'

  end

  get "how-to", to: "how_to#index"

  get 'home/index'

  match '/email_suggestions', to: 'email_suggestions#index', via: :get

	root "home#index"
end

app/models/request.rb
require 'elasticsearch/model'
class Request < ActiveRecord::Base
	include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
	belongs_to :user

	has_many :comments, :dependent => :destroy 
	has_many :images, :dependent => :destroy

	validates :requestor, :email, :org, :title, :details, :presence => true
	
	scope :completed, -> { where(status: 'Completed') }
	scope :open, -> { where.not(status: 'Completed') }
	accepts_nested_attributes_for :images, :allow_destroy => true

	def self.search(query)
	  __elasticsearch__.search(
	    {
	      query: {
	        multi_match: {
	          query: query,
	          fields: ['title^10', 'details', 'requestor', 'email', 'category']
	        }
	      }
	    }
	  )
	end
	paginates_per 10
end
Request.import

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :check_login
  before_action :set_request, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    if params[:search_term].nil?
      if admin_signed_in?
        if params[:status] == "completed"
          @requests = Request.completed.order(:created_at).page(params[:page])
        elsif params[:status] == "open"
          @requests = Request.open.order(:created_at).page(params[:page])
        else
          @requests = Request.order(:created_at).page(params[:page])
        end
      else
        if params[:status] == "completed"
          @requests = Request.completed.where("org = ?", @user.org).order(:created_at).page(params[:page])
        elsif params[:status] == "open"
          @requests = Request.open.where("org = ?", @user.org).order(:created_at).page(params[:page])
        else
          @requests = Request.where("org = ?", @user.org).order(:created_at).page(params[:page])
        end
      end
    else
      if admin_signed_in?
        if params[:status] == "completed"
          @requests = Request.completed.order(:created_at).search(params[:search_term]).records.page(params[:page])
        elsif params[:status] == "open"
          @requests = Request.search(params[:search_term]).records.where("status != ?", ["Completed"]).order(:created_at).page(params[:page])
        else
          @requests = Request.search(params[:search_term]).records.order(:created_at).page(params[:page])
        end
      else
        if params[:status] == "completed"
          @requests = Request.completed.where("org = ?", @user.org).search(params[:search_term]).records.page(params[:page])
        elsif params[:status] == "open"
          @requests = Request.where("org = ?", @user.org).search(params[:search_term]).records.where("status != ?", ["Completed"]).page(params[:page])
        else
          @requests = Request.where("org = ?", @user.org).search(params[:search_term]).records.order(:created_at).page(params[:page])
        end
      end
    end
    respond_with(@request)
  end

  def show
    @comments = @request.comments.all
    @comment = @request.comments.build
    respond_with(@request)
  end

  def new
    @request = Request.new
    respond_with(@request)
  end

  def edit
  end

  def create
    @request = Request.new(request_params)
    if user_signed_in?
      @request.user_id = @user.id
      @request.org = @user.org
    else
      @request.user_id = current_admin.id
    end
    get_trello_info
    description = create_description(request_params[:org], request_params[:reporter], request_params[:details])
    trello_card = Trello::Card.create(
      name: request_params[:title],
      list_id: @list,
      desc: description,
      pos: "top"
    )
    trello_card.card_labels = [ request_params[:category] ]
    trello_card.member_ids = [ "55b16198a7f9f5b30ea59a7b", "563afdd70fe34772fefe0b7d" ]
    trello_card.save
    @request.task_id = trello_card.id
    if @request.save
      if params[:request][:images]
        params[:request][:images].each { |image|
          @request.images.create(image: image)
        }
      end
    end
    RequestCreator.delay.send_request_notifier_email(@request)

    if params[:request][:org].to_i != 0
      redirect_to("/decision7/requests/#{@request.id}")
    else
      redirect_to("/ignitetek/requests/#{@request.id}")
    end
  end

  def update
    if @request.update(request_params)
      if request.fullpath[1..9].downcase == "decision7"
        redirect_to("/decision7/requests/#{@request.id}")
      else
        redirect_to("/ignitetek/requests/#{@request.id}")
      end
    else
      if request.fullpath[1..9].downcase == "decision7"
        redirect_to("/decision7/requests/#{@request.id}/edit")
      else
        redirect_to("/ignitetek/requests/#{@request.id}/edit")
      end
    end
  end

  def destroy
    @request.destroy
    if request.fullpath[1..9].downcase == "decision7"
      redirect_to("/decision7/requests")
    else
      redirect_to("/ignitetek/requests")
    end
  end

  private

    def create_description(org, reporter, details)
      return "Org- #{org}" + " Reporter- #{reporter} --> \n\n\n" + details
    end

    def get_trello_info
      @list = '568e914763989c9a48143f33'
    end

    def create_detailed_comment
      image_urls = ""
      @request.images.each { |image|
        image_urls += "#{image.image.url(:lrg)}, "
      }
      return "Org- #{@request.org}" + " Requestor- #{@request.requestor} --> " + @request.details
    end

    def check_login
      if user_signed_in? || admin_signed_in?
        @user = current_user
      else
        redirect_to :login
      end
    end

    def set_request
      @request = Request.find(params[:id])
    end

    def request_params
      params.require(:request).permit(:title, :details, :email, :priority, :requestor, :user_id, :org, :status, :category, :push_date, :search_term , images: [:image])
    end
end

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="six columns">
      <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title, :placeholder => "Enter Your Title" %>
      </div>
    </div>
    <div class="six columns">
      <div class="field">
        <%= f.label :category %><br>
        <%= f.select(:category, options_for_select(["Email", "Chat", "Social", "SMS", "Admin", "General Request"]), {}, { :class => 'u-full-width' } ) %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="six columns offset by two">
      <div class="field">
        <%= f.label :requestor %><br>
        <%= f.text_field :requestor, :required => true, :placeholder => "Enter Your Full Name" %>
      </div>
    </div>
    <div class="six columns">
      <div class="field">
        <%= f.label :priority %><br>
        <%= f.select(:priority, options_for_select(["Non-Service Impact", "Business Impact", "Severe Business Impact", "Outage"]), {}, { :class => 'u-full-width' } ) %>
      </div>
    </div>
  </div>
  <% if admin_signed_in? %>
  <div class="row">
    <div class="six columns">
      <div class="field">
        <%= f.label :status %><br>
        <%= f.select(:status, options_for_select(["Reported", "In Progress", "Testing", "Client Confirmation", "Monitoring", "Completed"]), {}, { :class => 'u-full-width' } ) %>
      </div>
    </div>
    <div class="six columns">
      <%= f.label :push_date %><br>
      <%= f.date_field :push_date %>
    </div>
  </div>
  <% end %>
  <div class="row">
    <% if admin_signed_in? %>
      <div class="six columns">
        <%= f.label :org %><br>
        <%= f.text_field :org %>
      </div>
    <% end %>
    <div class="six columns">
      <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email, :required => true, :placeholder => "Separate multiple email addresses with a ','", :class => 'search-field' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="twelve columns">
      <div class="field">
        <%= f.label :details %><br>
        <%= f.text_area :details, :required => true %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="twelve columns">
      <%= f.label :images %>
      <%= f.file_field :images, type: :file, multiple: true %>
    </div>
  </div>
  <%= f.hidden_field :user_id %>
  <div class="actions">
    <%= f.submit class: 'request-submit' %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<div class="row">
  <div class="twelve columns">
    <div class="five columns offset-by-four">
      <h1>Requests</h1>
    </div>
  </div>
  <ul class="row tabs">
    <% if request.fullpath[1..9].downcase == "decision7" %>
      <li class="two columns" id="tab1"><%= link_to 'All', "/decision7/requests", {:style=>'text-align:center; margin-top: 20px;'} %></li>
    <% else %>
      <li class="two columns" id="tab1"><%= link_to 'All', "/ignitetek/requests", {:style=>'text-align:center; margin-top: 20px;'} %></li>
    <% end %>
    <li class="two columns" id="tab2"><%= link_to 'Open', {:status => "open"}, {:style=>'text-align:center; margin-top: 20px;'} %></li>
    <li class="two columns" id="tab3"><%= link_to 'Completed', {:status => "completed"}, {:style=>'text-align:center; margin-top: 20px;'} %></li>
    <div class="three columns offset-by-two">
      <div class="field search">
        <%= text_field :search, '' %>
      </div>
    </div>
    <li class="one column search"><%= link_to 'Search', '', {:style=>'padding: 0px; text-align:center; margin-left: -3rem;', :class => "button", :id => "requestsearch"} %></li>
  </ul>
  <div class="twelve columns tab-content">
    <table class="u-full-width">
      <thead>
        <tr>
          <th>Status</th>
          <th>Date Reported</th>
          <th>Category</th>
          <th colspan="2">Title</th>
          <th>Push Date</th>
          <th colspan="2">Requestor</th>
          <th colspan="1"></th>
        </tr>
      </thead>

      <tbody>
        <% @requests.each do |request_item| %>
          <tr>
            <td><%= request_item.status %></td>
            <td><%= request_item.created_at  %></td>
            <td><%= request_item.category %></td>
            <td colspan="2"><%= request_item.title %></td>
            <td><%= request_item.push_date %></td>
            <td colspan="2"><%= request_item.requestor %></td>
            <% if request.fullpath[1..9].downcase == "decision7" %>
              <td class="table-button"><%= link_to 'Show', "/decision7/requests/#{request_item.id}", {:style=>'text-align:center; margin-top:1rem; margin-left: -1rem;', :class => "button"} %></td>
            <% else %>
              <td class="table-button"><%= link_to 'Show', "/ignitetek/requests/#{request_item.id}", {:style=>'text-align:center; margin-top:1rem; margin-left: -1rem;', :class => "button"} %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <br>
  <div class="three columns offset-by-five"><%= paginate @requests %></div>
  </div>
</div>

app/views/requests/new.html.erb
<br><br>
<% if request.fullpath[1..9].downcase == "decision7" %>
  <%= link_to 'Back', "/decision7/requests", {:style=>'text-align:center; margin-top:2rem;', :class => "button"} %>
<% else %>
  <%= link_to 'Back', "/ignitetek/requests", {:style=>'text-align:center; margin-top:2rem;', :class => "button"} %>
<% end %>

<h2>New request</h2>

<%= render 'form' %>

app/views/requests/show.html.erb
<% if request.fullpath[1..9].downcase == "decision7" %>
  <%= link_to 'Back', "/decision7/requests", {:style=>'text-align:center; margin-top:2rem;', :class => "button"} %>
<% else %>
  <%= link_to 'Back', "/ignitetek/requests", {:style=>'text-align:center; margin-top:2rem;', :class => "button"} %>
<% end %>
<% if admin_signed_in? %>
  | <%= link_to 'Edit', edit_request_path(@request), {:style=>'text-align:center; margin-top:2rem;', :class => "button"} %>
  | <%= link_to 'Destroy', @request, { method: :delete, :style=>'text-align:center; margin-top:2rem;', :class => "button", data: { confirm: 'Are you sure?' }} %>
<% end %>
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="eight columns">
    <h3><%= @request.title %></h3>
  </div>
</div>
<div class="row">
  <div class="twelve columns">
    <p>
      <strong><u>Request ID:</u></strong>
      <%= @request.id %>
    </p>
  </div>
  <div class="twelve columns">
    <p>
      <strong><u>Status:</u></strong>
      <%= @request.status %>
    </p>
  </div>
  <div class="twelve columns">
    <p>
      <strong><u>Priority:</u></strong>
      <%= @request.priority %>
    </p>
  </div>
  <div class="twelve columns">
    <p>
      <strong><u>Push Date:</u></strong>
      <%= @request.push_date %>
    </p>
  </div>
  <div class="twelve columns">
    <p>
      <strong><u>Org:</u></strong>
      <%= @request.org %>
    </p>
  </div>
  <div class="twelve columns">
    <p>
      <strong><u>Requestor:</u></strong>
      <%= @request.requestor %>
    </p>
  </div>
  <div class="twelve columns">
    <p>
      <strong><u>Email(s):</u></strong>
      <%= @request.email %>
    </p>
  </div>
</div>
<div class="row">
  <div class="twelve columns">
    <p>
      <strong><u>Category:</u></strong>
      <%= @request.category %>
    </p>
  </div>
</div>
<div class="row">
  <div class="twelve columns">
    <p>
      <strong><u>Details:</u></strong>
      <%= @request.details %>
    </p>
  </div>
</div>
<% if @request.images.exists? %>
  <div class="row">
    <div class="twelve columns">
      <div class="image-row">
          <div class="image-set">
            <p><strong><u>Images:</u></strong></p>
            <% @request.images.each do |image| %>
                <a class="without-caption image-link" data-lightbox="image-1" rel="shadowbox" href="<%=image.image.url %>" title=""><%= image_tag image.image.url(:med) %></a>
            <% end %>  
          </div>
      </div>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="twelve columns">
    <h3><u>Comments</u></h3>
    <% @comments.each do |comment| %>
      <div class="row">
        <a name="comment<%= comment.id %>"></a>
        <strong><u><%= comment.user_name %></u></strong> 
        <i class="comment-date"><%= time_ago_in_words(comment.created_at) + " Ago" %></i>
        <% if comment.images.exists? %>
          <div class="row">
            <div class="twelve columns">
              <div class="image-row">
                  <div class="image-set">
                    <p><strong><u>Images:</u></strong></p>
                    <% comment.images.each do |image| %>
                        <a class="without-caption image-link" data-lightbox="image-1" rel="shadowbox" href="<%=image.image.url %>" title=""><%= image_tag image.image.url(:med) %></a>
                    <% end %>  
                  </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="row">
        <br/>
        <p><%= comment.body %></p>
        <% if admin_signed_in? %>
          <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="twelve columns">
    <div class="button comments-button">Add Comments</div>
    <div class="six columns comments-form">
      <%= render 'comments/form' %>
    </div>
  </div>
</div>